apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: vishalgohripipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vishalgohripipelinesjavascriptdocker 
    spec:
      containers:
        - name: vishalgohripipelinesjavascriptdocker 
          image: acr99990.azurecr.io/vishalgohripipelinesjavascriptdocker
          ports:
          - containerPort: 8080